POST {{host}}/api/company/
Content-Type: application/json

{
  "name": "{{company-name}}",
  "employees": [
    {
      "name": "{{employee1-name}}",
      "email": "{{employee1-email}}"
    },
    {
      "name": "{{employee2-name}}",
      "email": "{{employee2-email}}"
    }
  ]
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.contentType.mimeType === "application/json", "Unexpected content type - MIME type");
    });

    client.global.set("company-id", response.body.id)
%}

###

GET {{host}}/api/company/{{company-id}}
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.contentType.mimeType === "application/json", "Unexpected content type - MIME type");
    });
%}